package templates

func CliSeederTemplate() []byte {
	return []byte(`// Code generated by goms.

package main

import (
	"log"
	"os"

	"github.com/raspiantoro/gormseeder"
	"{{ .SeedModuleName }}"
	"github.com/raspiantoro/goms/gomsloader"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func main() {
	var command *string

	if len(os.Args) > 1 {
		command = &os.Args[1]
	}

	dsn := "host={{ .Host }} user={{ .Username }} password={{ .Password }} dbname={{ .DbName }} port= {{ .Port }}"
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Info),
	})
	if err != nil {
		log.Fatalln(err)
	}

	seeds := gomsloader.LoadSeeder(&{{ .SeederSubDir }}.Seeds{})

	seeder := gormseeder.New(db, seeds)

	if command != nil && *command == "rollback" {
		if err = seeder.Rollback(); err != nil {
			log.Fatalln(err)
		}
	} else {
		if err = seeder.Seed(); err != nil {
			log.Fatalln(err)
		}
	}
}	
`)
}

func CliMigrationTemplate() []byte {
	return []byte(`// Code generated by goms.

package main

import (
	"log"
	"os"

	"github.com/go-gormigrate/gormigrate/v2"
	"{{ .MigrationModuleName }}"
	"github.com/raspiantoro/goms/gomsloader"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func main() {
	var command *string

	if len(os.Args) > 1 {
		command = &os.Args[1]
	}

	dsn := "host={{ .Host }} user={{ .Username }} password={{ .Password }} dbname={{ .DbName }} port= {{ .Port }}"
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Info),
	})
	if err != nil {
		log.Fatalln(err)
	}

	migrations := gomsloader.LoadMigration(&{{ .MigrationSubDir }}.Migrations{})

	migrator := gormigrate.New(db, gormigrate.DefaultOptions, migrations)

	if command != nil && *command == "rollback" {
		if err = migrator.RollbackLast(); err != nil {
			log.Fatalln(err)
		}
	} else {
		if err = migrator.Migrate(); err != nil {
			log.Fatalln(err)
		}
	}
}	
`)
}
