package templates

func MigrationsTemplate() []byte {
	return []byte(`// Code generated by goms. DO NOT EDIT.

package {{ .MigrationsSubDir }}

import "github.com/go-gormigrate/gormigrate/v2"

var Migrations = []*gormigrate.Migration{}
`)
}

func MigrationTemplate() []byte {
	return []byte(`// Code generated by goms. DO NOT RENAME THIS FILENAME.

package {{ .MigrationsSubDir }}

import (
	"gorm.io/gorm"
)

// don't rename this function
func {{ .UpFuncName }}(db *gorm.DB) error {
	// place your seed code here
	return nil
}

// don't rename this function
func {{ .DownFuncName }}(db *gorm.DB) error {
	// place your rollback code here
	return nil
}	
`)
}
