package templates

func SeedTemplate() []byte {
	return []byte(`// Code generated by goms. DO NOT EDIT.

package {{ .SeederSubDir }}

import (
	"path/filepath"
	"runtime"
)

type {{ .SeedsStructName }} struct{}

func (*{{ .SeedsStructName }}) Path() string {
	_, b, _, _ := runtime.Caller(0)
	basepath := filepath.Dir(b)

	return basepath
}
`)
}

func SeederTemplate() []byte {
	return []byte(`// Code generated by goms. DO NOT RENAME THIS FILENAME.

package {{ .SeederSubDir }}

import (
	"gorm.io/gorm"
)

// don't rename this function
func (s *{{ .SeedsStructName }}) {{ .UpFuncName }}(db *gorm.DB) error {
	// place your seed code here
	return nil
}

// don't rename this function
func (s *{{ .SeedsStructName }}) {{ .DownFuncName }}(db *gorm.DB) error {
	// place your rollback code here
	return nil
}	
`)
}
